// this file was generated by better-cmake
// allegrexplorer v0.0.1

#define allegrexplorer_NAME "allegrexplorer"
#define allegrexplorer_VERSION "0.0.1"
#define allegrexplorer_VERSION_MAJOR 0
#define allegrexplorer_VERSION_MINOR 0
#define allegrexplorer_VERSION_PATCH 1
